import { chromium } from "playwright";
import { buildInsights } from "./analysis";
import type { ScanResult } from "./types";

const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);

export async function renderPdf(scan: ScanResult, brand = "TRAXELON"): Promise<Buffer> {
  const insights = buildInsights(scan);
  const row = (items: unknown[]) => `<tr>${items.map((item) => `<td>${escape(item)}</td>`).join("")}</tr>`;
  const table = (headers: string[], rows: unknown[][]) => `<table><thead>${row(headers)}</thead><tbody>${rows.map(row).join("")}</tbody></table>`;
  const html = `<!doctype html><meta charset="utf-8"><style>
    body{font:12px Arial,sans-serif;color:#17232c;margin:35px}h1{font-size:27px;margin-bottom:3px}h2{font-size:17px;margin-top:25px;border-bottom:2px solid #23ae91;padding-bottom:6px}p{color:#5e7380}.stats{display:flex;gap:12px}.stat{border:1px solid #d8e2e4;padding:12px 16px;min-width:110px}.stat b{display:block;font-size:20px;color:#13866d}table{width:100%;border-collapse:collapse;table-layout:fixed}td{padding:7px;border-bottom:1px solid #e0e8eb;overflow-wrap:anywhere}thead td{background:#e7f4f0;font-weight:bold}.note{font-size:10px;color:#667b86}
  </style><h1>${escape(brand)} ${scan.demo ? "demo report" : "report"}</h1><p>${escape(scan.startUrl)} · ${escape(scan.completedAt)} · ${escape(scan.device ?? "desktop")} · ${escape(scan.mode)}${scan.demo ? " · Synthetic sample data" : ""}</p>
  <div class="stats">${[["Pages",scan.summary.pagesScanned],["Requests",scan.summary.requestsObserved],["Third parties",scan.summary.thirdPartyDomains],["Technologies",scan.summary.technologiesDetected]].map(([label, value]) => `<div class="stat"><b>${escape(value)}</b>${escape(label)}</div>`).join("")}</div>
  ${scan.lighthouse?.status === "completed" ? `<h2>Lighthouse scores and Web Vitals</h2>${table(["Category","Score"],Object.entries(scan.lighthouse.scores).map(([name,score])=>[name,score??"—"]))}${table(["Metric","Value"],Object.entries(scan.lighthouse.metrics).map(([name,metric])=>[name,metric.displayValue??"—"]))}` : ""}
  <h2>Technologies and vendors</h2>${table(["Name","Category","Confidence","Country","Evidence"],scan.technologies.slice(0,60).map((item)=>[item.name,item.category,item.confidence,item.destinationCountry??"—",item.evidence.map((e)=>e.value).join(", ")]))}
  <h2>Data destinations</h2>${table(["Vendor","Category","Country","Requests","Hosts"],insights.vendors.slice(0,60).map((item)=>[item.name,item.category,item.country??"—",item.requests,item.hosts.join(", ")]))}
  <h2>Pages</h2>${table(["URL","Status","Title","Load (ms)"],scan.pages.slice(0,100).map((item)=>[item.url,item.status??"—",item.title??"—",item.performance?.loadMs??"—"]))}
  <h2>Findings</h2>${table(["Finding","Page","Evidence","Confidence"],insights.findings.slice(0,100).map((item)=>[item.kind,item.page,item.evidence,item.confidence]))}
  <p class="note">Generated by ${escape(brand)} (traxelon.com/tools). This report contains observations from one synthetic browser scan. Field names are retained; request and cookie values are not.</p>`;
  const browser = await chromium.launch({ args: ["--no-sandbox", "--disable-dev-shm-usage"] });
  try {
    const page = await browser.newPage();
    await page.setContent(html);
    return await page.pdf({ format: "A4", printBackground: true, margin: { top: "14mm", bottom: "14mm", left: "12mm", right: "12mm" } });
  } finally { await browser.close(); }
}
